export const tokenIdToPfp = {
    "0": "/bayc/bayc-1.png",
    "1": "/bayc/bayc-2.png",
    "2": "/bayc/bayc-3.png",
    "3": "/bayc/bayc-11.png",
    "4": "/bayc/bayc-5.png",
    "5": "/bayc/bayc-6.png",
    "6": "/bayc/bayc-7.png",
    "7": "/bayc/bayc-8.png",
    "8": "/bayc/bayc-9.png",
    "9": "/bayc/bayc-10.png",
    "10": "/bayc/bayc-11.png",
    "11": "/bayc/bayc-12.png",
    "12": "/bayc/bayc-13.png",
    "13": "/bayc/bayc-14.png",
    "14": "/bayc/bayc-15.png",
    "15": "/bayc/bayc-16.png",
    "16": "/bayc/bayc-17.png",
    "17": "/bayc/bayc-18.png",
    "18": "/bayc/bayc-19.png",
    "19": "/bayc/bayc-20.png",
}